# Site settings
title: "Stefano Videsott"
description: "Personal website and portfolio of Stefano Videsott"
baseurl: ""
url: "https://StefanoVidesott.github.io"

# Theme
theme: jekyll-theme-minimal

# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

# Social
author:
  name: "Stefano Videsott"
  email: "ste.videsott@gmail.com"
  instagram: "stefano.videsott"
  discord: "apeiron_cz"

# Default settings
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: single
